package report

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/mdryaaan/flakehunter/internal/verdict"
)

// WriteDigest renders a short periodic summary, the format intended for a
// scheduled workflow that posts into an issue or a chat channel.
//
// Deliberately compact: a weekly digest that nobody reads is worse than none,
// so it leads with the single number that matters and the worst offenders.
func WriteDigest(w io.Writer, res ClassifiedResult, windowDays int) error {
	var b strings.Builder

	counts := res.CountsByCategory()
	total := 0
	for _, n := range counts {
		total += n
	}

	fmt.Fprintf(&b, "## Flake digest — last %d days\n\n", windowDays)
	fmt.Fprintf(&b, "`%s` · classified by %s\n\n", res.Repo, res.ProviderLabel())

	if total == 0 {
		b.WriteString("**No flaky occurrences detected.** Every job agreed with itself on every commit.\n")
		_, err := io.WriteString(w, b.String())
		return err
	}

	jobs := make(map[string]int)
	genuineBugs := 0
	for _, item := range res.Items {
		if item.Error != "" {
			continue
		}
		jobs[item.Occurrence.JobName]++
		if item.Verdict.Category == verdict.GenuineBug {
			genuineBugs++
		}
	}

	fmt.Fprintf(&b, "**%d flaky occurrence(s)** across **%d job(s)**.\n\n", total, len(jobs))

	if genuineBugs > 0 {
		fmt.Fprintf(&b, "> ⚠️ %d occurrence(s) look like a **genuine bug** masked by a rerun, "+
			"not infrastructure noise. Those should not be re-run to green.\n\n", genuineBugs)
	}

	b.WriteString("| Category | Count |\n| --- | ---: |\n")
	for _, category := range verdict.AllCategories() {
		if counts[category] == 0 {
			continue
		}
		fmt.Fprintf(&b, "| %s | %d |\n", category.Label(), counts[category])
	}
	b.WriteString("\n")

	type jobCount struct {
		name string
		n    int
	}
	ranked := make([]jobCount, 0, len(jobs))
	for name, n := range jobs {
		ranked = append(ranked, jobCount{name, n})
	}
	sort.SliceStable(ranked, func(i, j int) bool {
		if ranked[i].n != ranked[j].n {
			return ranked[i].n > ranked[j].n
		}
		return ranked[i].name < ranked[j].name
	})

	b.WriteString("**Noisiest jobs**\n\n")
	for i, jc := range ranked {
		if i >= 5 {
			break
		}
		fmt.Fprintf(&b, "%d. `%s` — %d occurrence(s)\n", i+1, jc.name, jc.n)
	}
	b.WriteString("\n<sub>Generated by [flakehunter](https://github.com/mdryaaan/flakehunter).</sub>\n")

	if _, err := io.WriteString(w, b.String()); err != nil {
		return fmt.Errorf("writing digest: %w", err)
	}
	return nil
}
