package report

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/mdryaaan/flakehunter/internal/verdict"
)

// WriteIssue renders a ready-to-paste GitHub issue body.
//
// Grouped by category rather than listed flat: a maintainer triaging flakes
// wants "here are the four network timeouts" as one decision, not four separate
// ones. Within a group the highest-confidence occurrence leads.
func WriteIssue(w io.Writer, res ClassifiedResult) error {
	var b strings.Builder

	byCategory := make(map[verdict.Category][]Classified)
	for _, item := range res.Items {
		if item.Error != "" {
			continue
		}
		byCategory[item.Verdict.Category] = append(byCategory[item.Verdict.Category], item)
	}

	total := 0
	for _, items := range byCategory {
		total += len(items)
	}

	fmt.Fprintf(&b, "## Flaky tests detected in `%s`\n\n", res.Repo)
	fmt.Fprintf(&b, "flakehunter found **%d flaky occurrence(s)** — jobs that produced both a pass "+
		"and a failure on the same commit.\n\n", total)
	fmt.Fprintf(&b, "Classified by `%s`.\n\n", res.ProviderLabel())

	if res.Baseline {
		b.WriteString("> Verdicts below come from the deterministic rule-based baseline, " +
			"not a language model.\n\n")
	}

	if total == 0 {
		b.WriteString("Nothing to action. 🎉\n")
		_, err := io.WriteString(w, b.String())
		return err
	}

	categories := make([]verdict.Category, 0, len(byCategory))
	for category := range byCategory {
		categories = append(categories, category)
	}
	sort.SliceStable(categories, func(i, j int) bool {
		if categories[i].Severity() != categories[j].Severity() {
			return categories[i].Severity() > categories[j].Severity()
		}
		return categories[i] < categories[j]
	})

	for _, category := range categories {
		items := byCategory[category]
		sort.SliceStable(items, func(i, j int) bool {
			return items[i].Verdict.Confidence > items[j].Verdict.Confidence
		})

		m := verdict.MitigationFor(category)
		fmt.Fprintf(&b, "### %s (%d)\n\n", category.Label(), len(items))
		fmt.Fprintf(&b, "**%s** _(owner: %s)_\n\n", m.Summary, m.Owner)

		for _, item := range items {
			occ := item.Occurrence
			fmt.Fprintf(&b, "- [ ] `%s` — %s _(commit `%s`, %.0f%% failure rate, confidence %.2f)_\n",
				occ.JobName, firstSentence(item.Verdict.Explanation),
				shortSHA(occ.HeadSHA), occ.FailureRate*100, item.Verdict.Confidence)
		}

		b.WriteString("\n<details><summary>Suggested steps</summary>\n\n")
		for _, step := range m.Steps {
			fmt.Fprintf(&b, "1. %s\n", step)
		}
		b.WriteString("\n</details>\n\n")
	}

	b.WriteString("---\n<sub>Generated by [flakehunter](https://github.com/mdryaaan/flakehunter).</sub>\n")

	if _, err := io.WriteString(w, b.String()); err != nil {
		return fmt.Errorf("writing issue body: %w", err)
	}
	return nil
}

func firstSentence(s string) string {
	s = strings.TrimSpace(s)
	if idx := strings.IndexAny(s, ".!?"); idx > 0 {
		return s[:idx+1]
	}
	return s
}
